// This file is auto-generated by the ASH WARE ETEC Linker.
//    !!!   DO NOT EDIT THIS FILE   !!!
// Copyright (C) 2015 ASH WARE, Inc. 

// It contains macros containing data initialization information.
// The host side code uses this initialization information
// to initialize global data and also the private channel frames.
// Note that it is designed to be included multiple times into
// the same file.

// Global Memory Initialization Data Macros

#ifndef __GLOBAL_MEM_INIT32
#define __GLOBAL_MEM_INIT32( addr , val )
#endif

// macro name ( address_or_offset , data_value )
__GLOBAL_MEM_INIT32( 0x0000 , 0x00000000 )
__GLOBAL_MEM_INIT32( 0x0004 , 0x00000000 )

// I2C_slave Channel Frame Initialization Data Macros

#ifndef __I2C_slave_CHAN_FRAME_INIT32
#define __I2C_slave_CHAN_FRAME_INIT32( addr , val )
#endif

// macro name ( address_or_offset , data_value )
__I2C_slave_CHAN_FRAME_INIT32( 0x0000 , 0x00000000 )
__I2C_slave_CHAN_FRAME_INIT32( 0x0004 , 0x00000000 )
__I2C_slave_CHAN_FRAME_INIT32( 0x0008 , 0x00000000 )
__I2C_slave_CHAN_FRAME_INIT32( 0x000c , 0x00000000 )
__I2C_slave_CHAN_FRAME_INIT32( 0x0010 , 0x00000000 )
__I2C_slave_CHAN_FRAME_INIT32( 0x0014 , 0x00000000 )
__I2C_slave_CHAN_FRAME_INIT32( 0x0018 , 0x00000000 )
__I2C_slave_CHAN_FRAME_INIT32( 0x001c , 0x00000000 )
__I2C_slave_CHAN_FRAME_INIT32( 0x0020 , 0x00000000 )
__I2C_slave_CHAN_FRAME_INIT32( 0x0024 , 0x00000000 )
__I2C_slave_CHAN_FRAME_INIT32( 0x0028 , 0x00000000 )
__I2C_slave_CHAN_FRAME_INIT32( 0x002c , 0x00000000 )
__I2C_slave_CHAN_FRAME_INIT32( 0x0030 , 0x00000000 )
__I2C_slave_CHAN_FRAME_INIT32( 0x0034 , 0x00000000 )
__I2C_slave_CHAN_FRAME_INIT32( 0x0038 , 0x00000000 )
__I2C_slave_CHAN_FRAME_INIT32( 0x003c , 0x00000000 )
// I2C_master Channel Frame Initialization Data Macros

#ifndef __I2C_master_CHAN_FRAME_INIT32
#define __I2C_master_CHAN_FRAME_INIT32( addr , val )
#endif

// macro name ( address_or_offset , data_value )
__I2C_master_CHAN_FRAME_INIT32( 0x0000 , 0x00000000 )
__I2C_master_CHAN_FRAME_INIT32( 0x0004 , 0x00000000 )
__I2C_master_CHAN_FRAME_INIT32( 0x0008 , 0x00000000 )
__I2C_master_CHAN_FRAME_INIT32( 0x000c , 0x00000000 )
__I2C_master_CHAN_FRAME_INIT32( 0x0010 , 0x00000000 )
__I2C_master_CHAN_FRAME_INIT32( 0x0014 , 0x00000000 )
__I2C_master_CHAN_FRAME_INIT32( 0x0018 , 0x00000000 )
__I2C_master_CHAN_FRAME_INIT32( 0x001c , 0x00000000 )
__I2C_master_CHAN_FRAME_INIT32( 0x0020 , 0x00000000 )
__I2C_master_CHAN_FRAME_INIT32( 0x0024 , 0x00000000 )
__I2C_master_CHAN_FRAME_INIT32( 0x0028 , 0x00000000 )
__I2C_master_CHAN_FRAME_INIT32( 0x002c , 0x00000000 )
__I2C_master_CHAN_FRAME_INIT32( 0x0030 , 0x00000000 )
__I2C_master_CHAN_FRAME_INIT32( 0x0034 , 0x00000000 )
__I2C_master_CHAN_FRAME_INIT32( 0x0038 , 0x00000000 )
__I2C_master_CHAN_FRAME_INIT32( 0x003c , 0x00000000 )
